= Frege Goodness へようこそ

== 日本語版まえがき

本書は、Dierk Koenig 氏による https://www.gitbook.com/book/dierk/fregegoodness[Frege Goodness] の日本語翻訳版です。原著者の了承の下で公開しています。

https://github.com/Frege/frege[Frege] (フレーゲ) は、Haskell と極めて近い構文・意味論を持ちつつも JVM 上で動作する、純粋関数型プログラミング言語です。今のところあまりメジャーな言語とはいえませんが、本書がきっかけになって Frege に触る人が少しでも増えれば嬉しい限りです。

なお、原著と同じくこの日本語版のソースコードも GitHub にホスティングされています。日本語版に関して何かお気付きの方は https://github.com/y-taka-23/frege-goodness-jp/issues[日本語版のレポジトリ] に issue を出していただけると幸いです。もちろん、直接のプルリクエストも歓迎しています。

それでは、ようこそ Frege の世界へ！

== 原著まえがき

本書では、いくつかの章に分けて Frege の特徴を一つずつ紹介します。ひとつひとつの章はあえて短めにしてあるので、通勤電車の中でも、あるいは昼食を食べながらでも読み切ってしまえるはずです。

本書の目的に対してこの GitBook は理想的な媒体でした。GitBook で配信することにより、読者は更新通知を登録して最新の記事を公開直後に読むことができます。しかしブログとは異なり、すべての章を手元に置いた上で閲覧したり検索したりすることも可能です。

さらに、Web、スマートフォン、タブレット、iBooks、Kindle など、各種デバイスもサポートされています。

なお、 https://www.gitbook.com/book/y-taka-23/frege-goodness-jp[日本語版] の翻訳 (訳註 : つまりこの文書のこと) も Yuto Takahashi (@y-taka-23) によって進行中です。

=== 準中級者向け

読者層としては、Haskell/Frege の基本的な文法要素については知っている _準中級者_ を想定しています。

本書の目的は、最初の一歩を通過したその後に来る好奇心をくすぐることです。この次は何をすればいい？ 典型的なそして Frege 的な使い方とは？ 特定のユースケースでなぜ Frege を使うべきなのか？ 昔から純粋関数型プログラミングに不向きだと思われている分野で Frege を実用的に使うには？ Frege のキモはどこにある？

一言で言えば、Frege の威力を完全に引き出すためのすべてがここにあります。

=== 執筆協力

本書の原稿は GitHub で管理されています。フィードバック、質問、改善提案などがありましたら https://github.com/Dierk/FregeGoodness/issues[Issue] に登録してください。

最近、GitBook はパラグラフと紐づいたドキュメント内コメントをサポートするようになりました。パラグラフにカーソルを当てると「+」ボタンが現れるので、クリックすればコメントを書き始められます (訳註 : 原著のみ。翻訳版では無効に設定されています)。

本書に協力して頂ける方からの https://github.com/Dierk/FregeGoodness/pulls[プルリクエスト] も歓迎しています。

原著者へのコンタクトは Twitter アカウント https://twitter.com/mittie[@mittie] あるいは各種 https://github.com/Frege/frege#contact[Frege 関連チャンネル] から可能です。

=== クレジット

Frege Goodness のフォーマットは、Goovy-/Grails-/Gradle- の各 Goodness シリーズを長きに渡って執筆している @MrHaki にインスパイアされたものです。本書では氏の例に沿ってプログラミング言語 Frege に関するトピックを説明しています。
